### ISSUE TITLE
Page Component

### ISSUE THREAD

**Issue by Barritosaurus** [RiwajMainali/in.Vintori#10]
We should utilize a 'page' system for the application, this will look good on phones and browser. Pages will hold unique UI (Inventory, Options, et cetera) and should be swapped by a state system in the application.

This is a somewhat challenging component and it is recommended that you complete other minor components before making this.

Blocked by #1, #2, #3, #5, #9

**Comment by kasiyo** [comment]
completed 2023 Jan 12
